// @ts-nocheck
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/8HN1zKtp6As
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import {
  CardTitle,
  CardDescription,
  CardHeader,
  CardContent,
  Card,
} from "@/components/ui/card"
import { Separator } from "@/components/ui/separator"
import { ResponsiveLine } from "@nivo/line"
import { ResponsiveBar } from "@nivo/bar"

export function attendance() {
  return (
    <div className="flex flex-col w-full min-h-screen bg-gray-100 dark:bg-gray-800">
      <header className="bg-white dark:bg-gray-950 shadow-sm">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-4 flex items-center justify-between">
          <div className="flex items-center gap-4">
            <Link className="text-lg font-bold" href="#">
              Student Dashboard
            </Link>
            <nav className="hidden md:flex items-center gap-4 text-sm font-medium">
              <Link
                className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                href="#">
                Attendance
              </Link>
              <Link
                className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                href="#">
                Assignments
              </Link>
              <Link
                className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                href="#">
                Grades
              </Link>
              <Link
                className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
                href="#">
                Schedule
              </Link>
            </nav>
          </div>
          <div className="flex items-center gap-4">
            <Button className="rounded-full" size="icon" variant="ghost">
              <MailsIcon className="w-6 h-6 text-gray-500 dark:text-gray-400" />
              <span className="sr-only">Notifications</span>
            </Button>
            <Avatar className="w-8 h-8 border">
              <AvatarImage alt="Avatar" src="/placeholder-user.jpg" />
              <AvatarFallback>JD</AvatarFallback>
            </Avatar>
          </div>
        </div>
      </header>
      <main className="flex-1 max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          <Card>
            <CardHeader>
              <CardTitle>Attendance</CardTitle>
              <CardDescription>
                Track your attendance and share your location.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex items-center justify-between">
                <div>
                  <div className="text-4xl font-bold">92%</div>
                  <div className="text-gray-500 dark:text-gray-400">
                    Attendance
                  </div>
                </div>
                <Button size="sm" variant="secondary">
                  <CheckIcon className="w-4 h-4" />
                  Mark Attendance
                </Button>
              </div>
              <Separator className="my-4" />
              <div className="flex items-center justify-between">
                <div>
                  <div className="text-4xl font-bold">4</div>
                  <div className="text-gray-500 dark:text-gray-400">
                    Absences
                  </div>
                </div>
                <Button size="sm" variant="outline">
                  <MapPinIcon className="w-4 h-4" />
                  Share Location
                </Button>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Assignments</CardTitle>
              <CardDescription>
                Submit your assignments before the deadline.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="flex items-center justify-between">
                <div>
                  <div className="text-4xl font-bold">8</div>
                  <div className="text-gray-500 dark:text-gray-400">
                    Pending
                  </div>
                </div>
                <Button size="sm" variant="secondary">
                  <UploadIcon className="w-4 h-4" />
                  Submit Assignment
                </Button>
              </div>
              <Separator className="my-4" />
              <div className="flex items-center justify-between">
                <div>
                  <div className="text-4xl font-bold">12</div>
                  <div className="text-gray-500 dark:text-gray-400">
                    Completed
                  </div>
                </div>
                <Button size="sm" variant="outline">
                  <CalendarIcon className="w-4 h-4" />
                  View Deadlines
                </Button>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Overview</CardTitle>
              <CardDescription>
                A summary of your attendance and assignments.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <div className="text-4xl font-bold">92%</div>
                  <div className="text-gray-500 dark:text-gray-400">
                    Attendance
                  </div>
                </div>
                <div>
                  <div className="text-4xl font-bold">20</div>
                  <div className="text-gray-500 dark:text-gray-400">
                    Assignments
                  </div>
                </div>
                <div>
                  <div className="text-4xl font-bold">A-</div>
                  <div className="text-gray-500 dark:text-gray-400">
                    Average Grade
                  </div>
                </div>
                <div>
                  <div className="text-4xl font-bold">4</div>
                  <div className="text-gray-500 dark:text-gray-400">
                    Absences
                  </div>
                </div>
              </div>
              <Separator className="my-4" />
              <div className="grid gap-4">
                <LineChart className="w-full aspect-[4/3]" />
                <BarChart className="w-full aspect-[4/3]" />
              </div>
            </CardContent>
          </Card>
        </div>
        <div className="mt-8">
          <div>
            <div>Upcoming Assignment Deadline</div>
            <div>
              Your "Introduction to Programming" assignment is due tomorrow at
              11:59 PM.
            </div>
            <div>
              <Button size="sm" variant="secondary">
                <CalendarIcon className="w-4 h-4" />
                View Assignment
              </Button>
            </div>
          </div>
          <div>
            <div>Attendance Reminder</div>
            <div>
              Don't forget to mark your attendance for today's class. You have
              10 minutes left to do so.
            </div>
            <div>
              <Button size="sm" variant="secondary">
                <CheckIcon className="w-4 h-4" />
                Mark Attendance
              </Button>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}

function BarChart(props) {
  return (
    <div {...props}>
      <ResponsiveBar
        data={[
          { name: "Jan", count: 111 },
          { name: "Feb", count: 157 },
          { name: "Mar", count: 129 },
          { name: "Apr", count: 150 },
          { name: "May", count: 119 },
          { name: "Jun", count: 72 },
        ]}
        keys={["count"]}
        indexBy="name"
        margin={{ top: 0, right: 0, bottom: 40, left: 40 }}
        padding={0.3}
        colors={["#2563eb"]}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16,
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 4,
          tickPadding: 16,
        }}
        gridYValues={4}
        theme={{
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
          grid: {
            line: {
              stroke: "#f3f4f6",
            },
          },
        }}
        tooltipLabel={({ id }) => `${id}`}
        enableLabel={false}
        role="application"
        ariaLabel="A bar chart showing data"
      />
    </div>
  )
}

function CalendarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  )
}

function CheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M20 6 9 17l-5-5" />
    </svg>
  )
}

function LineChart(props) {
  return (
    <div {...props}>
      <ResponsiveLine
        data={[
          {
            id: "Desktop",
            data: [
              { x: "Jan", y: 43 },
              { x: "Feb", y: 137 },
              { x: "Mar", y: 61 },
              { x: "Apr", y: 145 },
              { x: "May", y: 26 },
              { x: "Jun", y: 154 },
            ],
          },
          {
            id: "Mobile",
            data: [
              { x: "Jan", y: 60 },
              { x: "Feb", y: 48 },
              { x: "Mar", y: 177 },
              { x: "Apr", y: 78 },
              { x: "May", y: 96 },
              { x: "Jun", y: 204 },
            ],
          },
        ]}
        margin={{ top: 10, right: 10, bottom: 40, left: 40 }}
        xScale={{
          type: "point",
        }}
        yScale={{
          type: "linear",
        }}
        axisTop={null}
        axisRight={null}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16,
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 5,
          tickPadding: 16,
        }}
        colors={["#2563eb", "#e11d48"]}
        pointSize={6}
        useMesh={true}
        gridYValues={6}
        theme={{
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
          grid: {
            line: {
              stroke: "#f3f4f6",
            },
          },
        }}
        role="application"
      />
    </div>
  )
}

function MailsIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="16" height="13" x="6" y="4" rx="2" />
      <path d="m22 7-7.1 3.78c-.57.3-1.23.3-1.8 0L6 7" />
      <path d="M2 8v11c0 1.1.9 2 2 2h14" />
    </svg>
  )
}

function MapPinIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z" />
      <circle cx="12" cy="10" r="3" />
    </svg>
  )
}

function UploadIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="17 8 12 3 7 8" />
      <line x1="12" x2="12" y1="3" y2="15" />
    </svg>
  )
}
